language: csharp
solution: Scheme.sln
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
  - nuget restore
script:
  - chmod +x ./packages/FsLexYacc.6.1.0/build/*.exe
  - xbuild ./Scheme.sln
  - cd ./Tests/bin/Debug
  - mono Tests.exe $(cat Tests.txt)
notifications:
  email: false
